---
framework: jest
preRun:
     command:
        - npm ci
preMerge:
  pattern:
    - "./src/core/utils/markdown.test.js"
postMerge:
  pattern: 
    - "./src/core/utils/markdown.test.js"
postRun:
     command:
        - node --version
version: 1.2
